### ISSUE TITLE
Installation Questions

### ISSUE THREAD

**Issue by scoobynz** [SirCmpwn/broca#3]
Hello,

Installing on Debian 9 virtual machine. I have installed pip3 to install any dependencies required and have already installed aiohttp as it was required. I now get to;

`scoobynz@Testbox-Debian:~/src/broca$ ./broca-daemon
Traceback (most recent call last):
  File "./broca-daemon", line 4, in <module>
    from broca.reaper import reaper
  File "/home/scoobynz/src/broca/broca/reaper.py", line 13
    print(f"Reaping {conn.uuid}")
                               ^
SyntaxError: invalid syntax
`
Many thanks.

**Comment by SirCmpwn** [comment]
Your Python is not new enough. You need Python 3.6.

**Comment by scoobynz** [comment]
Thanks. Installed phython3.6. Updated broca.ini to change 127.0.0.1 to the ip of the server on my LAN hosting synapse. Looks good, thanks.
